### ISSUE TITLE
Getting skeleton and synapse data from Pyknossoss

### ISSUE THREAD

**Issue by dadanhan** [adwanner/PyKNOSSOS#1]
Hi, I was just wondering how to get skeleton and synapse data from the .nmx files?

**Comment by adwanner** [comment]
Hi, for the record: NMX-file is a zip-archive container in which annotations and skeletons are saved in individual NML-files, the native KNOSSOS file format, which is XML-based. Each skeleton consists of 3D nodes (vertices) connected by edges. The NML format was originally described in https://www.nature.com/articles/nn.2868?page=5

**Comment by dadanhan** [comment]
Hi, thanks for the answer. I managed to read in the skeletons and now I am wondering if synapse information was also included in 'Dataset 2: Skeleton reconstructions of neurons in the OB' from https://www.nature.com/articles/sdata2016100 
How would I be able to get skeleton reconstructions and synapse locations along the skeletons from PyKNOSSOS/dataset 2?

**Comment by adwanner** [comment]
the synapses have been annotated in a follow-up study (https://www.nature.com/articles/s41593-019-0576-z). I can add them to the zenodo repository if you are interested. Note, however, some of the synapses have been annotated redundantly. A detailed description of the synapse annotation procedure can be found in the paper.

**Comment by dadanhan** [comment]
Hi that would be great to have some synapse data! I've also sent you an email from my academic address.

**Comment by adwanner** [comment]
where did you send it to? I have not received anything yet...

dadanhan ***@***.***> schrieb am Do., 2. Dez. 2021, 18:49:

**Comment by dadanhan** [comment]
Hi, I sent it to the @fmi.ch email that was the corresponding email in the Nature articles. Is it ok? Please let me know a more recent one if that is not valid.

**Comment by dadanhan** [comment]
Hi Adrian, sorry I was looking at the older Nature publication. I realized that you are now in Princeton and have sent you another email. Please let me know if this is correct.
